# Generated by Django 5.0.4 on 2024-04-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0002_product_product_slug_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(db_index=True, default=0, null=True),
        ),
    ]
